"""
CSV to Visualization Tool Converter
Converts Cadmium CSV output to the format required by DEVS WebViewer

Usage: python convert_csv_to_viz.py <input_csv> <output_prefix>
Example: python convert_csv_to_viz.py ../simulation_results/T1_single_lifecycle_output.csv Airport
"""

import sys
import re
from collections import defaultdict

def seconds_to_timestamp(seconds):
    """Convert seconds (float or int) to HH:MM:SS:mmm format"""
    total_ms = int(float(seconds) * 1000)
    hours = total_ms // 3600000
    remaining = total_ms % 3600000
    minutes = remaining // 60000
    remaining = remaining % 60000
    secs = remaining // 1000
    ms = remaining % 1000
    return f"{hours:02d}:{minutes:02d}:{secs:02d}:{ms:03d}"

def parse_state_data(data_str):
    """Convert {phase=IDLE, size=0, busy=0, sigma=inf} to phase: IDLE & size: 0 & busy: 0 & sigma: inf"""
    if not data_str or data_str.strip() == '':
        return None

    # Remove curly braces
    data_str = data_str.strip()
    if data_str.startswith('{') and data_str.endswith('}'):
        data_str = data_str[1:-1]

    # Split by comma and convert format
    parts = []
    for part in data_str.split(','):
        part = part.strip()
        if '=' in part:
            key, value = part.split('=', 1)
            parts.append(f"{key.strip()}: {value.strip()}")

    if parts:
        return ' & '.join(parts)
    return None

def convert_csv(input_file, output_prefix):
    """Convert CSV file to state and messages files"""

    states = []  # List of (timestamp, model_name, state_str)
    messages = []  # List of (timestamp, model_name, port, value)

    # Track all models for state output
    all_models = set()
    model_states = defaultdict(dict)  # model_name -> {time -> state}

    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Skip header line(s)
    start_idx = 0
    for i, line in enumerate(lines):
        if line.startswith('sep=') or line.startswith('time;'):
            start_idx = i + 1
            continue
        if start_idx > 0:
            break

    # Parse CSV data
    current_time = None
    time_states = defaultdict(dict)  # time -> {model -> state}
    time_messages = defaultdict(list)  # time -> [(model, port, value)]

    for line in lines[start_idx:]:
        line = line.strip()
        if not line:
            continue

        parts = line.split(';')
        if len(parts) < 5:
            continue

        time_val = parts[0]
        model_id = parts[1]
        model_name = parts[2]
        port_name = parts[3]
        data = parts[4] if len(parts) > 4 else ''

        all_models.add(model_name)

        # If port_name is empty, this is a state update
        if not port_name or port_name.strip() == '':
            state_str = parse_state_data(data)
            if state_str:
                time_states[time_val][model_name] = state_str
        else:
            # This is an output message
            time_messages[time_val].append((model_name, port_name, data))

    # Write state file
    state_filename = f"{output_prefix}_output_state.txt"
    with open(state_filename, 'w') as f:
        # Get sorted unique times
        all_times = sorted(set(time_states.keys()) | set(time_messages.keys()),
                          key=lambda x: float(x) if x != 'inf' else float('inf'))

        # Track current state for each model
        current_model_states = {}

        for time_val in all_times:
            timestamp = seconds_to_timestamp(time_val)

            # Update current states with any new states at this time
            if time_val in time_states:
                for model, state in time_states[time_val].items():
                    current_model_states[model] = state

            # Write timestamp
            f.write(f"{timestamp}\n")

            # Write state for each model we've seen
            for model in sorted(current_model_states.keys()):
                f.write(f"State for model {model} is {current_model_states[model]}\n")

    print(f"Created: {state_filename}")

    # Write messages file
    messages_filename = f"{output_prefix}_output_messages.txt"
    with open(messages_filename, 'w') as f:
        all_times = sorted(time_messages.keys(),
                          key=lambda x: float(x) if x != 'inf' else float('inf'))

        for time_val in all_times:
            timestamp = seconds_to_timestamp(time_val)
            f.write(f"{timestamp}\n")

            for model_name, port_name, value in time_messages[time_val]:
                # Format: [PortName: {value}] generated by model modelname
                f.write(f"[{port_name}: {{{value}}}] generated by model {model_name}\n")

    print(f"Created: {messages_filename}")

    # Print summary
    print(f"\nSummary:")
    print(f"  Models found: {', '.join(sorted(all_models))}")
    print(f"  Time points: {len(all_times)}")
    print(f"  Output messages: {sum(len(msgs) for msgs in time_messages.values())}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python convert_csv_to_viz.py <input_csv> <output_prefix>")
        print("Example: python convert_csv_to_viz.py ../simulation_results/T1_single_lifecycle_output.csv Airport")
        sys.exit(1)

    input_file = sys.argv[1]
    output_prefix = sys.argv[2]

    convert_csv(input_file, output_prefix)
    print("\nDone! Now you need to create:")
    print("  1. {output_prefix}.ma - Model structure file")
    print("  2. diagram.svg - Visual diagram of your model")
